---
title: "6-two_vars"
author: "Huize Zhang"
date: "14/03/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, 
                      warning = FALSE, 
                      message = FALSE, 
                      cache = TRUE)
library(tidyverse)
library(magick)
library(patchwork)
load(here::here("sherry", "data", "data_mult.rda"))
load(here::here("sherry", "data", "mult_geodesic.rda"))
load(here::here("sherry", "data", "mult_object.rda"))
#load(here::here("sherry", "data", "mult_object_better.rda"))
#load(here::here("sherry", "data", "mult_object_better_random.rda"))
```

```{r}
origin_dt_bi <- data_mult %>% as_tibble() %>% 
  gather(names, values) %>%
  mutate(names = as_factor(names),
         names = fct_relevel(names, levels = c("x1", "x2", "x7","x8", "x9", "x10")))

origin_dt_bi %>% 
  ggplot(aes(x = values)) +
  geom_histogram(binwidth = 0.5) +
  geom_density(aes(y=0.5 * ..count..)) +
  facet_wrap(vars(names), ncol = 3)

```



## `search_geodesic()`


```{r}
mult_object <- mult_object %>% 
  mutate(info2 = ifelse(info %in% c("best_line_search",
                                     "best_direction_search"), 
                        "best", "normal"),
         info3 = ifelse(info2 == "normal", as.character(info),
                        str_sub(info, start = 6L, end = -1L))) %>% 
  mutate(info3 = fct_relevel(info3, c("start", "direction_search", "line_search", "interpolation")), 
         info2 = as.factor(info2))

# colour by parts of optimisation (static)
mult_releveled <- mult_object %>%
  filter(info != "interpolation") 

mult_object %>% 
  ggplot(aes(x= PC1, y = PC2, col = info)) +
  geom_point() +
  geom_point(data = mult_releveled) +
  theme(aspect.ratio = 1)
```


```{r}
# colour the interpolation from all the bases
mult_interpolate <- mult_object %>% 
  filter(info == "interpolation") %>% 
  mutate(id2 = lag(id),
         info4 = ifelse(is.na(id2), "start", 
                        ifelse(id2 - id == -1, "interpolation", "target")))

# # interpolation path
ggplot(data =mult_interpolate,
       aes(x= PC1, y = PC2)) +
  geom_point(aes(col = info4)) +
  geom_path(linetype = "dashed")
```

```{r geo-animate}
# colour by parts of optimisation (animation)
mult_animate <- mult_object %>%
  mutate(loop = ifelse(info == "start", 1, loop)) %>% 
  group_by(tries, loop, info3) %>%
  mutate(animate_id = group_indices())

geo_animate <- mult_animate %>%
  ggplot(aes(x = PC1, y = PC2, col = info)) +
  geom_point() +
  theme(aspect.ratio = 1, 
        legend.position = "none") +
  gganimate::transition_time(animate_id) +
  gganimate::shadow_mark()

p1 <- gganimate::animate(geo_animate, fps = 2)

index_val_animate <- mult_animate %>% 
  ggplot(aes(x= animate_id, y= index_val, col = info)) + 
  geom_jitter(width = 0.0005) + 
  theme(aspect.ratio = 1) +
  gganimate::transition_time(animate_id) + 
  gganimate::shadow_mark()

p2 <- gganimate::animate(index_val_animate, fps = 2)

a_mgif <- image_read(p1)
b_mgif <- image_read(p2)

new_gif <- image_append(c(a_mgif[1], b_mgif[1]))
for(i in 2:100){
  combined <- image_append(c(a_mgif[i], b_mgif[i]))
  new_gif <- c(new_gif, combined)
}

new_gif

```

```{r}
gg_color_hue <- function(n) {
  hues = seq(15, 375, length = n + 1)
  hcl(h = hues, l = 65, c = 100)[1:n]
}

mult_path <- mult_animate %>% 
  ungroup() %>% 
  ggplot(aes(x= animate_id, y= index_val, col = info)) + 
  geom_point()
  #facet_zoom(x = (tries == 7 & info %in% c("direction_search",
  #                                               "best_direction_search")))
   #ylim = c(0.7866, 0.7875)

last_tries <- mult_animate$tries[which.max(mult_animate$loop)]

direction <- mult_animate %>% 
  filter(tries == last_tries, info != "line_search") %>% 
  ggplot(aes(x= animate_id, y= index_val, col = info)) + 
  geom_point() + 
  xlim(1, max(mult_animate$animate_id)) + 
  scale_color_manual(values = c(gg_color_hue(6)[2:3], gg_color_hue(6)[5:6])) + 
  theme(legend.position =  "none")
  
direction/ mult_path + 
  plot_layout(heights = c(1, 2), guides = "collect")

```

```{r index-val-id-animation, eval = FALSE}
mult_animate %>% 
  ggplot(aes(x = id, y = index_val, col = info))  + 
  geom_point() + 
  gganimate::transition_time(id) + 
  gganimate::shadow_mark()

 
mult_path_id <- mult_animate %>% 
  ggplot(aes(x = id, y = index_val, col = info))  + 
  geom_point()

direction_id <- mult_animate %>% 
  filter(tries > 7, info != "line_search") %>% 
  ggplot(aes(x= id, y= index_val, col = info)) + 
  geom_point() + 
  xlim(1, max(mult_animate$id)) + 
  scale_color_manual(values = c(gg_color_hue(6)[2:3], gg_color_hue(6)[5:6])) + 
  theme(legend.position =  "none")
  
direction_id/ mult_path_id + 
  plot_layout(heights = c(1, 2), guides = "collect")

 
#gridExtra::grid.arrange(p1, p2, index_val_line, nrow = 2)
```
